name: CI
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Lint Glue job
        run: |
          python -m pip install ruff
          ruff check glue_jobs
      - name: Terraform fmt & validate
        uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.8.5 }
      - run: cd infrastructure && terraform fmt -check && terraform init -backend=false && terraform validate
